### PR TITLE
Make test failure value readable

### PR DESCRIPTION
**Pull request by sjabasti**

### CODE REVIEW

**Comment by guillaumevincent** [comment]
Actual code:

image

Your patch:

image

did I miss something?

The output is a text less readable

Also github repository is just a mirror. To contribute you need to create a review on software factory https://softwarefactory-project.io/r/gitweb?p=dci-ui.git;a=summary

Thank you

**Comment by sjabasti** [comment]
I missed that it would also change the task log my mistake. However the same \<Pre\> is also used in src/jobs/tests/TestsCase.js where it is displayed on a white background (which is what I was trying to fix):

image


Tomorrow, Ill close this pr and convert it into a issue/bug. Where is the best place to submit issues to which are DCI related?

**Comment by guillaumevincent** [comment]
You can leave an issue on github, I will fix this one
Thank you for the report and the PR

**Comment by guillaumevincent** [comment]
The review fixing the problem https://softwarefactory-project.io/r/#/c/16755/

**Comment by sjabasti** [comment]
Looks much better now, thank you

**Pull request closed without merging**
